#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");
const { buildChunks } = require("./chunk");

const ROOT = path.resolve(__dirname, "..");
const CACHE_PATH = path.join(ROOT, "data", "embedding-cache.json");
const SEED_PATH = path.join(ROOT, "data", "seed.sql");
const INDEX_PATH = path.join(ROOT, "data", "index.json");
const EMBEDDING_MODEL = "@cf/baai/bge-base-en-v1.5";
const BATCH_SIZE = 50;
const MAX_ATTEMPTS = 3;

function normalize(vector) {
  const length = Math.hypot(...vector);
  if (!Number.isFinite(length) || length === 0) throw new Error("Embedding vector has zero or invalid magnitude");
  return vector.map((value) => value / length);
}

function readCache() {
  if (!fs.existsSync(CACHE_PATH)) return { model: EMBEDDING_MODEL, dimensions: null, embeddings: {} };
  const cache = JSON.parse(fs.readFileSync(CACHE_PATH, "utf8"));
  if (!cache || typeof cache !== "object" || Array.isArray(cache) || typeof cache.embeddings !== "object") {
    throw new Error("data/embedding-cache.json must be an object keyed by content_hash");
  }
  return cache;
}

function extractVectors(payload, expected) {
  const result = payload.result ?? payload;
  const candidates = [result.data, result.embedding, result.embeddings, result];
  const vectors = candidates.find((candidate) => Array.isArray(candidate) && Array.isArray(candidate[0]));
  if (!vectors || vectors.length !== expected || vectors.some((vector) => !vector.every(Number.isFinite))) {
    throw new Error(`Unexpected Workers AI embedding response: ${JSON.stringify(payload).slice(0, 500)}`);
  }
  return vectors;
}

function delay(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}

async function embedBatch(texts) {
  const accountId = process.env.CF_ACCOUNT_ID;
  const apiToken = process.env.CF_API_TOKEN;
  if (!accountId || !apiToken) {
    throw new Error("Set CF_ACCOUNT_ID and CF_API_TOKEN (Workers AI:Read) before running npm run index");
  }

  let lastError;
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt += 1) {
    try {
      const response = await fetch(
        `https://api.cloudflare.com/client/v4/accounts/${accountId}/ai/run/${EMBEDDING_MODEL}`,
        { method: "POST", headers: { Authorization: `Bearer ${apiToken}`, "Content-Type": "application/json" }, body: JSON.stringify({ text: texts }) },
      );
      const payload = await response.json();
      if (response.ok && payload.success !== false) return extractVectors(payload, texts.length).map(normalize);
      lastError = new Error(`Workers AI embedding request failed (${response.status})`);
    } catch (error) {
      lastError = error;
    }
    if (attempt < MAX_ATTEMPTS) await delay(250 * (2 ** (attempt - 1)));
  }
  throw new Error(`Workers AI embedding request failed after ${MAX_ATTEMPTS} attempts: ${String(lastError)}`);
}

function sqlText(value) {
  return `'${value.replace(/'/g, "''")}'`;
}

function vectorBlob(vector) {
  const buffer = Buffer.allocUnsafe(vector.length * 4);
  for (let i = 0; i < vector.length; i += 1) buffer.writeFloatLE(vector[i], i * 4);
  return `X'${buffer.toString("hex")}'`;
}

function buildSeedSql(chunks) {
  const schema = `-- Generated by scripts/index.js. Do not edit by hand.\n\nCREATE TABLE IF NOT EXISTS chunks (\n  id TEXT PRIMARY KEY,\n  doc_id TEXT NOT NULL,\n  source TEXT NOT NULL,\n  heading TEXT NOT NULL,\n  chunk_index INTEGER NOT NULL,\n  content TEXT NOT NULL,\n  embed_text TEXT NOT NULL,\n  token_count INTEGER NOT NULL,\n  content_hash TEXT NOT NULL,\n  embedding BLOB NOT NULL\n);\n\nCREATE VIRTUAL TABLE IF NOT EXISTS chunks_fts USING fts5(\n  id UNINDEXED,\n  content,\n  heading,\n  tokenize = 'unicode61'\n);\n\nDELETE FROM chunks_fts;\nDELETE FROM chunks;\n\n`;

  const inserts = chunks.map((chunk) => {
    const values = [
      sqlText(chunk.id), sqlText(chunk.doc_id), sqlText(chunk.source), sqlText(chunk.heading),
      String(chunk.chunk_index), sqlText(chunk.content), sqlText(chunk.embed_text),
      String(chunk.token_count), sqlText(chunk.content_hash), vectorBlob(chunk.embedding),
    ].join(", ");
    return `INSERT INTO chunks (id, doc_id, source, heading, chunk_index, content, embed_text, token_count, content_hash, embedding) VALUES (${values});\nINSERT INTO chunks_fts (id, content, heading) VALUES (${sqlText(chunk.id)}, ${sqlText(chunk.content)}, ${sqlText(chunk.heading)});`;
  });
  return `${schema}${inserts.join("\n")}\n`;
}

async function main() {
  const chunks = buildChunks();
  const cache = readCache();
  const cacheMatchesModel = cache.model === EMBEDDING_MODEL;
  const missing = chunks.filter((chunk) => !cacheMatchesModel || !Array.isArray(cache.embeddings[chunk.content_hash]));

  for (let start = 0; start < missing.length; start += BATCH_SIZE) {
    const batch = missing.slice(start, start + BATCH_SIZE);
    console.log(`Embedding ${start + 1}-${start + batch.length} of ${missing.length} changed chunks`);
    const vectors = await embedBatch(batch.map((chunk) => chunk.embed_text));
    const dimensions = vectors[0]?.length;
    if (!dimensions || vectors.some((vector) => vector.length !== dimensions)) throw new Error("Embedding dimensions are inconsistent");
    if (cache.dimensions && cache.dimensions !== dimensions) throw new Error("Embedding dimension changed; remove data/embedding-cache.json before re-indexing");
    cache.dimensions = dimensions;
    batch.forEach((chunk, index) => { cache.embeddings[chunk.content_hash] = vectors[index]; });
  }

  const activeHashes = new Set(chunks.map((chunk) => chunk.content_hash));
  for (const hash of Object.keys(cache.embeddings)) if (!activeHashes.has(hash)) delete cache.embeddings[hash];
  cache.model = EMBEDDING_MODEL;
  const indexed = chunks.map((chunk) => ({ ...chunk, embedding: cache.embeddings[chunk.content_hash] }));
  if (indexed.some((chunk) => !Array.isArray(chunk.embedding))) throw new Error("Missing embedding after indexing");

  fs.mkdirSync(path.dirname(CACHE_PATH), { recursive: true });
  fs.writeFileSync(CACHE_PATH, `${JSON.stringify(cache)}\n`);
  fs.writeFileSync(SEED_PATH, buildSeedSql(indexed));
  fs.writeFileSync(INDEX_PATH, `${JSON.stringify({ embedding_model: EMBEDDING_MODEL, dimensions: cache.dimensions, chunks: indexed.map(({ id, content_hash, token_count }) => ({ id, content_hash, token_count })) }, null, 2)}\n`);
  console.log(`Wrote ${indexed.length} indexed chunks to data/seed.sql (${missing.length} embedded, ${chunks.length - missing.length} reused)`);
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}

module.exports = { BATCH_SIZE, EMBEDDING_MODEL, buildSeedSql, normalize, vectorBlob };
